### ISSUE TITLE
Feature request: explain what transformations `fix_text` chooses

### ISSUE THREAD

**Issue by gjm11** [rspeer/python-ftfy#162]
Suppose I have some garbled text. I feed it to FTFY and it, well, fixes that for me. Great! I now have ungarbled text. But next I would like to ...

* ... figure out what bit of the pipeline that produced the text is broken
* ... tell whoever gave me the text "It looks as if you've done X"
* ... just out of curiosity, understand what the heck is going on.

For any of these, I want to know _what it did_. So far as I can see, FTFY doesn't currently provide a way to get that information. I know that _somehow_ some text that was meant to be A ended up as B, but I don't know how.

That would be a nice thing to have. Perhaps `fix_text` would get a new parameter saying whether to explain what it's doing. Perhaps a new function entirely. Perhaps the explanation should be written to stdout, a bit like `explain_unicode`, or perhaps there's some more programmatically-useful representation that could be returned. Any of those seems to me like it would be OK.

**Comment by rspeer** [comment]
I should check -- are you aware of `ftfy.fixes.fix_encoding_and_explain`? That's the function that does what you're asking if the only thing being fixed is encoding mixups. But it does make sense to ask for the same thing for `fix_text`.

It would require redesigning the way `fix_text` works so that it keeps track of the state of the text after each fix. This feature fit nicely into `fix_encoding` because it already had to keep track of which steps it's applying.

It's definitely a good idea for a future major version.

**Comment by gjm11** [comment]
I was somehow _not_ aware of `ftfy.fixes.fix_encoding_and_explain`, no; thanks very much for that. But, indeed, it's not quite what I was after -- it seems to me that since `fix_text` is, as the docs put it, "the main function of `ftfy`", it would be very nice for there to be a way to find out what _that_ is doing.

("Future major version" seems like a very reasonable target.)

**Comment by rspeer** [comment]
Fixed in 6.0.
