### ISSUE TITLE
Possible latin1 mojibake

### ISSUE THREAD

**Issue by StyXman** [rspeer/python-ftfy#178]
I got this dir with miscoded filenames:

```
(foo) mdione@diablo:~/tmp/foo$ ls -l /home/mdione/media/music/Los\ Fabulosos\ Cadillacs/Chau/
total 32208
-rw-r--r-- 1 mdione mdione 4278572 ene 31  2007 '01-Basta de llamarme as'$'\355''.mp3'
-rw-r--r-- 1 mdione mdione 4985132 ene 31  2007 '16-Demasiada presi'$'\363''n.mp3'
```

Checking with `hd` we can see what bytes we have there:

```
(foo) mdione@diablo:~/tmp/foo$ ls -l /home/mdione/media/music/Los\ Fabulosos\ Cadillacs/Chau/ | hd
00000030  6e 65 20 33 31 20 20 32  30 30 37 20 30 31 2d 42  |ne 31  2007 01-B|
00000040  61 73 74 61 20 64 65 20  6c 6c 61 6d 61 72 6d 65  |asta de llamarme|
00000050  20 61 73 ed 2e 6d 70 33  0a 2d 72 77 2d 72 2d 2d  | as..mp3.-rw-r--|
[...]
00000160  44 65 6d 61 73 69 61 64  61 20 70 72 65 73 69 f3  |Demasiada presi.|
00000170  6e 2e 6d 70 33 0a 2d 72  77 2d 72 2d 2d 72 2d 2d  |n.mp3.-rw-r--r--|
```

So what `ls` reports as `'$'\355''` (WTF) is `ed`. The original letter is `í` (`&iacute;`)

And then:
```
In [4]: 'í'.encode('latin1')
Out[4]: b'\xed'

In [10]: 'ó'.encode('latin1')
Out[10]: b'\xf3'
```

but:

```
In [8]: os.listdir('/home/mdione/media/music/Los Fabulosos Cadillacs/Chau/')[-1]
Out[8]: '01-Basta de llamarme as\udced.mp3'

In [9]: ftfy.fix_and_explain(_)
Out[9]: ExplainedText(text='01-Basta de llamarme as�.mp3', explanation=[('apply', 'fix_surrogates')])

In [11]: os.listdir('/home/mdione/media/music/Los Fabulosos Cadillacs/Chau/')[-4]
Out[11]: '16-Demasiada presi\udcf3n.mp3'

In [12]: ftfy.fix_and_explain(_)
Out[12]: ExplainedText(text='16-Demasiada presi�n.mp3', explanation=[('apply', 'fix_surrogates')])
```

Maybe it's because `python3` fuggits up (why `\udced` and `\udcf3`?), but maybe `ftfy` drops the ball here too?

**Comment by rspeer** [comment]
You have filenames that aren't in UTF-8, but are instead in ISO-8859-1. Most filesystems impose an encoding on their files so that filenames can be consistently decoded as Unicode, but POSIX filesystems don't.

ftfy says up front that its job is to fix problems in Unicode, not to fix when your problem is that you don't have Unicode.

Python lets you use bytestrings as filenames also, and that's what you'll need to do here. I recommend writing a Python script that reads the filenames as bytestrings, decodes them as ISO-8859-1, and then renames the files to the UTF-8 encodings of the filenames.

**Comment by StyXman** [comment]
Ah, so ftfy goes the other way around, from utf-encoded-in-latin1 back to utf. Sounds reasonable. Thanks for picking up an issue even I forgot about :)
