### ISSUE TITLE
Incorrect mojibake fix for "– DrÃ¥"

### ISSUE THREAD

**Issue by thecnoNSMB** [rspeer/python-ftfy#202]
This is the minimized example, in context I was cleaning up "Bremer/Mccoy – DrÃ¥ber" from a tracklist. "– DrÃ¥" should decode to "– Drå" (the full example decodes to "Bremer/Mccoy – Dråber"), but instead it decodes to "РDr̴ ", interpreting the em-dash and its following space as additional mojibake for some reason while applying the wrong fix to the correct mojibake. All the more curiously, it accepts "– Drå" as correct and does not attempt to fix anything, nor does it make any changes to "– Dr". Apparently something about that specific mojibake causes it to interpret the dash differently? Attached is a small text file with the relevant strings as they are on my computer: [ftfy example.txt](https://github.com/rspeer/python-ftfy/files/14319534/ftfy.example.txt)

**Comment by rspeer** [comment]
Thanks! I partially fixed this in v6.2.0.

This string can be inconsistently decoded as Latin-1/UTF-8 mojibake (the en dash is not mojibaked but the å is), or mostly consistently decoded as MacRoman mojibake (it only requires interpreting the space as a non-breaking space). Because of the ambiguity and the weak evidence, I don't think this string can safely be fixed. In fact, decoding the Ã¥ as Latin-1 led to a false positive in another test case, with some kind of leetspeak in a language I don't recognize.

But I can at least prevent this, and strings like it, from being incorrectly decoded as MacRoman.
